spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

server.forward-headers-strategy=native
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

sigin.core.url=${SIGIN_CORE_URL}