spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${PGUSER}
    password: ${PGPASSWORD}

server:
  port: 8081
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

sigin:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}

    core:
      url: ${SIGIN_CORE_URL}
      canal-venda-id: ${SIGIN_CORE_CANAL_VENDA_ID}
      login: ${SIGIN_CORE_LOGIN}
      senha: ${SIGIN_CORE_SENHA}