spring.application.name=sigin-delivery
spring.datasource.url=jdbc:postgresql://localhost:5432/sigin_delivery
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true