spring:
  application:
    name: sigin-delivery

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

sigin:
  cors:
    allowed-origins: ${SIGIN_CORS_ALLOWED_ORIGINS}
