spring.config.import=optional:file:../sigin-runtime/secrets/delivery.properties

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/sigin_delivery
spring.datasource.username=postgres
spring.datasource.password=admin

sigin.core.url=http://localhost:8080

sigin.core.canal-venda-id=2

sigin.core.login=${SIGIN_CORE_LOGIN}
sigin.core.senha=${SIGIN_CORE_SENHA}